const SOURCES = {
  bhre: {name:"HCSP · BHRe, 2019",url:"https://www.hcsp.fr/Explore.cgi/Telecharger?NomFichier=hcspr20191211_actualidesrecommarelativauxbhre.pdf",desc:"Repérage et dépistage à l’admission (R1, R8), prise en charge, contacts et transmission des informations (R65 à R70, R78)."},
  resp: {name:"SF2H · Transmission respiratoire, 2024",url:"https://www.sf2h.net/k-stock/data/uploads/2024/reco_respiratoire/Prevention_transmission_voie_respiratoire_RECOS_SF2H.pdf",desc:"Analyse du risque respiratoire, ajustement des APR (R14–R15), précautions respiratoires et suspicion de tuberculose (R22–R25)."},
  ps: {name:"SF2H · Précautions standard, 2017",url:"https://www.santepubliquefrance.fr/sites/default/files/rdd/document/HY_XXV_PS_versionSF2H.pdf",desc:"Hygiène des mains, indications des gants, protection de la tenue et du visage, prévention de l’exposition aux produits biologiques."},
  reb: {name:"COREB · Le REB en bref",url:"https://www.coreb.infectiologie.com/fr/le-reb-en-bref.html",desc:"Dépister, protéger, prendre en charge, alerter et orienter. Symptômes, exposition et incubation compatibles avec une définition de cas."},
  procedure: {name:"COREB · Procédure générique, 2018",url:"https://www.coreb.infectiologie.com/fr/procedure-generique-reb.html",desc:"Cadre de prise en charge des patients suspects REB, adapté aux alertes et aux organisations locales."},
  diph2011: {name:"HCSP · Conduite à tenir devant une diphtérie, 2011",url:"https://www.hcsp.fr/explore.cgi/hcspr20110304_conduitediphterie.pdf",desc:"Socle de prise en charge de la diphtérie, à lire avec les compléments de 2021 : suspicion ORL, prélèvements, isolement et contacts de C. diphtheriae tox+. Les parties modifiées en 2021 prévalent sur ce texte ancien."},
  diph2021: {name:"HCSP · Diphtérie : compléments, 2021",url:"https://www.hcsp.fr/Explore.cgi/Telecharger?NomFichier=hcspa20210910_avrelacoteauduncadediac.pdf",desc:"Signalement immédiat des suspicions ORL, définition des cas à notifier, recherche urgente du gène tox et mesures différenciées selon l’espèce et le statut tox."},
  diphcnr: {name:"Institut Pasteur · FAQ du CNR diphtérie",url:"https://www.pasteur.fr/fr/sante-publique/centres-nationaux-reference/cnr/corynebacteries-du-complexe-diphtheriae/foire-aux-questions",desc:"Recherche urgente du gène tox, antibiothérapie dès la suspicion et indications de l’antitoxine, notamment avant confirmation en présence de signes toxiniques. Consultée le 30 septembre 2026."},
  ebola: {name:"COREB · FHV Ebola, 16 septembre 2026",url:"https://www.coreb.infectiologie.com/UserFiles/File/procedures/20260916-fiche-coreb-fhv-ebola.pdf",desc:"Repérage à moins de 21 jours d’une exposition compatible, protection, conduite en SAU non ESR et orientation spécialisée. La géographie des alertes doit être revérifiée en soins réels."},
  mersdef: {name:"Santé publique France · Définition MERS-CoV, juin 2024",url:"https://www.santepubliquefrance.fr/content/download/634569/file/Mers_CoV_Definition_de_cas_juin_2024.pdf",desc:"Définition de cas, dont infection respiratoire aiguë de toute gravité après exposition professionnelle dans un établissement de santé d’un pays à risque, dans les 14 jours avant les symptômes."},
  mersprec: {name:"HCSP · MERS-CoV, avril 2015",url:"https://www.hcsp.fr/Explore.cgi/Telecharger?NomFichier=hcspr20150424_infectionMersCovdefcasmodpec.pdf.",desc:"Référentiel ancien de prise en charge : précautions Air et Contact, circuit des prélèvements et expertise. Utilisé ici pour les mesures de protection, pas pour la définition de cas, actualisée en 2024."},
  zooflu: {name:"COREB · Grippes zoonotiques, novembre 2025",url:"https://www.coreb.infectiologie.com/UserFiles/File/20250703-grippes-zoonotiques-coreb.pdf",desc:"Date affichée dans le document : 13 novembre 2025. Conjonctivite isolée après exposition avérée, protections renforcées REB, PCR et sous-typage ; équipe expérimentée."},
  zoospf: {name:"Santé publique France · Grippe aviaire, 2026",url:"https://www.santepubliquefrance.fr/grippe-aviaire/notre-action",desc:"Page actualisée le 26 mars 2026 : classement possible/probable/confirmé, signalement immédiat des cas probables à l’ARS et confirmation par le CNR."},
  malaria: {name:"INRS · EFICATT Paludisme",url:"https://www.inrs.fr/dam/eficatt/FicheEficatt/EFICATT_Paludisme-2.pdf",desc:"Transmission, signes de gravité et diagnostic sanguin urgent : résultat dans les deux heures, sans attendre un pic fébrile. Consulté le 30 septembre 2026."}
};
// Les indices corrects sont réordonnés à l’affichage. Le score est pédagogique, non validant.
const CASES = [
{
 id:"epc",code:"01",time:"18:40",location:"Accueil des urgences",title:"Le détail dans le dossier",
 topic:"Risque de portage d’EPC",duration:"5 min",level:"Repérer & prévenir",
 intro:"Un patient de 67 ans consulte pour une rétention aiguë d’urine. Il est stable. L’équipe prépare son installation et le sondage.",
 patient:"Patient A · 67 ans",vitals:[["T°","36,8 °C"],["PA","138/78"],["FC","86/min"],["SpO₂","97 % AA"]],
 clues:[
  ["Interroger sur les soins récents","« Il y a six semaines, j’ai été hospitalisé cinq jours à l’étranger pour une fracture. J’ai reçu des antibiotiques. »"],
  ["Lire le dossier de liaison","Aucun résultat de dépistage BHRe disponible. Aucun antécédent de portage connu. Les documents de l’hospitalisation sont incomplets."],
  ["Évaluer le besoin de soins","Douleur sus-pubienne et globe vésical. Le senior confirme la nécessité d’un sondage sans retard évitable."]
 ],
 steps:[
  {dim:"Repérage",label:"Interrogatoire ciblé",q:"Quelle information fait rechercher en priorité un risque de portage de BHRe ?",multi:false,correct:[0],critical:true,
   options:["Une hospitalisation d’au moins 24 h à l’étranger au cours des 12 derniers mois.","La nationalité du patient, même sans exposition aux soins.","La rétention urinaire, qui prouve un portage digestif.","L’absence de fièvre, qui exclut un portage."],
   explanation:"L’hospitalisation de cinq jours à l’étranger, six semaines auparavant, répond au critère de dépistage. Un portage peut être asymptomatique : il ne s’agit pas d’un diagnostic d’infection. Le repérage repose sur les expositions, pas sur la nationalité.",
   good:"Vous repérez le risque avant l’installation en secteur partagé.",
   bad:"Le risque de portage n’est pas correctement identifié. Le dossier est repris avec le senior avant l’orientation.",
   takeaway:"Demander les hospitalisations à l’étranger dans les 12 derniers mois.",sources:["bhre"]},
  {dim:"Protection",label:"Décisions immédiates",q:"Que mettez-vous en place sans attendre le résultat du dépistage ?",multi:true,correct:[0,1,2],critical:true,
   options:["Chambre individuelle et précautions complémentaires contact, en plus des précautions standard.","Dépistage digestif par écouvillonnage rectal pour EPC et ERG, selon le circuit du laboratoire.","Information du senior et de l’équipe, organisation du soin urgent et transmission tracée à l’EOH pour reprise à ses horaires de présence.","Reporter le sondage jusqu’au résultat pour éviter tout risque.","Antibiothérapie de décolonisation systématique."],
   explanation:"Le HCSP recommande chambre individuelle et PCC dès l’admission, avec dépistage digestif EPC/ERG. Le senior organise immédiatement les mesures selon le protocole local ; l’EOH reprend le suivi à ses horaires de présence. Le risque BHRe ne doit pas provoquer de perte de chance. Un risque de portage ne justifie pas une antibiothérapie de décolonisation systématique.",
   good:"Le circuit est sécurisé et la prise en charge de la rétention se poursuit.",
   bad:"Le senior vous fait corriger le circuit : prévenir la transmission ne doit ni attendre le résultat, ni retarder inutilement les soins.",
   takeaway:"Anticiper les mesures sans retarder les soins nécessaires.",sources:["bhre"]},
  {dim:"Gestes sûrs",label:"Les gants ne font pas tout",q:"Vous venez de terminer un soin exposant aux excreta, avec des gants. Avant de toucher l’ordinateur, que faites-vous ?",multi:false,correct:[0],critical:true,
   options:["Retirer les gants, réaliser l’hygiène des mains et utiliser l’ordinateur avec des mains propres.","Frictionner les gants puis saisir la prescription.","Garder les gants car le patient est potentiellement porteur.","Ajouter une seconde paire de gants."],
   explanation:"Les gants ne remplacent pas l’hygiène des mains et ne sont pas désinfectés pour être réutilisés. Après retrait, une friction hydroalcoolique est réalisée sur mains non visiblement souillées ; si elles sont souillées, lavage à l’eau et au savon. Le port de gants dépend du soin, pas de la seule présence dans la chambre.",
   good:"Vous interrompez la chaîne de transmission entre le soin et le poste informatique.",
   bad:"L’ordinateur peut devenir un relais de transmission. La séquence est interrompue pour retirer les gants et réaliser l’hygiène des mains.",
   takeaway:"Retirer les gants au bon moment, puis réaliser l’hygiène des mains.",sources:["ps"]},
  {dim:"Coordination",label:"Passage de relais",q:"Le dépistage est positif à une EPC, sans infection documentée. Le patient doit être hospitalisé. Quelle transmission retenez-vous ?",multi:false,correct:[0],critical:false,
   options:["Informer le patient et l’unité receveuse, tracer le portage et organiser les mesures avec le senior ; transmettre à l’EOH pour le suivi et le signalement à ses horaires de présence.","Transférer discrètement pour éviter de bloquer l’admission.","Traiter systématiquement le résultat par un antibiotique.","Refuser tout transfert jusqu’à trois prélèvements négatifs."],
   explanation:"Le portage doit être expliqué au patient et transmis oralement et par écrit aux professionnels concernés. Le senior prépare immédiatement le transfert et les mesures selon le protocole local, sans attendre la disponibilité de l’EOH. Celle-ci reprend l’évaluation de l’organisation et des contacts à ses horaires de présence ; le responsable du signalement réalise e-SIN après avis EOH. Le portage seul n’est pas une indication d’antibiothérapie.",
   good:"L’unité receveuse peut préparer l’accueil sans découverte tardive du statut.",
   bad:"Une transmission incomplète ou un blocage du transfert compromet le parcours. Le senior reprend immédiatement la coordination ; le suivi est transmis à l’EOH à ses horaires de présence.",
   takeaway:"Portage ≠ infection ; transmettre le statut et préparer l’accueil.",sources:["bhre"]}
 ]
},
{
 id:"tb",code:"02",time:"20:15",location:"Box de consultation",title:"Une toux qui dure",
 topic:"Suspicion de tuberculose contagieuse",duration:"5 min",level:"Protéger sans attendre",
 intro:"Une patiente de 42 ans présente une toux depuis cinq semaines, un amaigrissement et des sueurs nocturnes. Elle attend encore dans un box ouvert.",
 patient:"Patiente B · 42 ans",vitals:[["T°","38,1 °C"],["PA","118/72"],["FC","94/min"],["SpO₂","96 % AA"]],
 clues:[
  ["Préciser les symptômes","La patiente rapporte quelques crachats striés de sang. Aucun traitement antituberculeux n’est en cours."],
  ["Consulter l’imagerie","La radiographie montre une image excavée du lobe supérieur droit. Aucun résultat microbiologique n’est encore disponible."],
  ["Vérifier les locaux","Une chambre individuelle, porte fermée, est disponible. Le senior vérifie les locaux adaptés en s’appuyant sur le protocole et les caractéristiques de ventilation documentées avec l’EOH et les services techniques en amont ; une difficulté immédiate est escaladée selon le circuit local."]
 ],
 steps:[
  {dim:"Repérage",label:"De la suspicion à l’action",q:"Quel est le bon seuil pour engager les précautions respiratoires ?",multi:false,correct:[0],critical:true,
   options:["Les arguments cliniques et radiologiques suffisent à agir avant la documentation microbiologique.","Un examen direct positif est indispensable avant de protéger.","Il faut attendre la culture, seule preuve suffisante.","L’absence de détresse respiratoire exclut une contagiosité."],
   explanation:"La recommandation R23 de la SF2H (2024) prévoit des précautions complémentaires respiratoires renforcées devant des arguments cliniques et/ou radiologiques évocateurs de tuberculose pulmonaire, avant la documentation. « Bacillifère » ne se déduit pas de la seule clinique : le scénario commence au stade de suspicion.",
   good:"Vous déclenchez les mesures dès la suspicion, sans attendre une preuve de contagiosité.",
   bad:"Attendre les résultats laisserait persister une exposition évitable. Les mesures sont engagées maintenant avec le senior.",
   takeaway:"Suspicion clinique ou radiologique : protéger avant confirmation.",sources:["resp"]},
  {dim:"Protection",label:"Protéger les voies respiratoires",q:"Quels éléments retenez-vous pour cette prise en charge ?",multi:true,correct:[0,1,2],critical:true,
   options:["Chambre individuelle, porte fermée, avec ventilation adaptée à vérifier.","APR FFP2 pour le professionnel avant d’entrer, avec contrôle d’étanchéité à chaque mise en place.","Masque à usage médical pour la patiente lors d’un déplacement indispensable, si toléré.","Masque chirurgical seul pour le professionnel, même dans la chambre.","Porte ouverte pour surveiller la patiente depuis le couloir."],
   explanation:"Les précautions respiratoires renforcées associent protection par FFP2 et mesures d’environnement. Le FFP2 se met avant l’entrée et se retire après la sortie. Le fit-check à chaque mise en place ne remplace pas le fit-test qui aide à choisir un modèle adapté. Le circuit et le niveau de protection sont réévalués, notamment si une résistance MDR/XDR est suspectée.",
   good:"La protection du professionnel et le contrôle de la source sont organisés.",
   bad:"Un élément essentiel de protection manque ou est contredit. Le senior reprend la préparation avant l’entrée.",
   takeaway:"FFP2 ajusté avant l’entrée ; chambre et ventilation adaptées.",sources:["resp"]},
  {dim:"Gestes sûrs",label:"Prélèvement respiratoire",q:"Un recueil d’expectoration est prescrit. Où et comment l’organisez-vous ?",multi:false,correct:[0],critical:true,
   options:["Dans un lieu adapté au risque respiratoire, avec protection des intervenants et circuit convenu avec le laboratoire.","Dans les toilettes communes pour préserver l’intimité.","Au poste de soins pour surveiller facilement la patiente.","Dans le couloir, près d’une fenêtre ouverte."],
   explanation:"Le recueil de sécrétions respiratoires doit préserver les précautions respiratoires et éviter l’exposition des autres patients. Une expectoration induite ou une bronchoscopie nécessite une analyse spécifique du risque et des conditions techniques. Le jeu ne remplace pas le protocole local de prélèvement.",
   good:"Le prélèvement est organisé sans déplacer le risque vers les espaces communs.",
   bad:"Le lieu choisi exposerait d’autres personnes. Le recueil est réorganisé dans un environnement adapté.",
   takeaway:"Ne pas déplacer un prélèvement exposant vers un espace partagé.",sources:["resp","ps"]},
  {dim:"Coordination",label:"Un examen à l’extérieur du service",q:"Une imagerie complémentaire est jugée indispensable. Quelle organisation choisissez-vous ?",multi:false,correct:[0],critical:false,
   options:["Prévenir l’imagerie et le transport, organiser un circuit limitant les contacts et maintenir la protection adaptée.","Envoyer la patiente dans la file d’attente habituelle avec le bon d’examen.","Annuler tout examen, même indispensable.","Faire lever les précautions dès le premier examen direct négatif, sans réévaluation."],
   explanation:"Les sorties sont limitées au strict nécessaire, pas interdites quand un examen est indispensable. Les intervenants doivent connaître les mesures requises et anticiper le parcours. Une levée des précautions relève d’une décision médicale argumentée intégrant les résultats et le contexte, pas d’un automatisme sur un seul examen.",
   good:"L’examen utile reste accessible, avec un circuit et des équipes préparés.",
   bad:"Le parcours n’est pas suffisamment sécurisé ou un soin utile est perdu. Une coordination avec le service receveur est nécessaire.",
   takeaway:"Limiter les déplacements et prévenir avant tout transfert nécessaire.",sources:["resp"]}
 ]
},
{
 id:"epi",code:"03",time:"22:05",location:"Salle d’accueil des urgences vitales",title:"Avant le premier geste",
 topic:"EPI pour une intubation à risque respiratoire",duration:"5 min",level:"Choisir & utiliser les EPI",
 intro:"Un patient de 58 ans, avec infection respiratoire transmissible suspectée, se dégrade malgré l’oxygénothérapie. Le senior décide une intubation urgente. Des projections abondantes de sécrétions sont anticipées.",
 patient:"Patient C · 58 ans",vitals:[["T°","39,2 °C"],["PA","105/65"],["FR","34/min"],["SpO₂","88 % sous O₂"]],
 clues:[
  ["Préciser votre rôle","Le senior expérimenté intube. Vous préparez le matériel et assistez au geste au contact du patient. L’équipe limite les intervenants non indispensables."],
  ["Évaluer l’exposition","Geste au contact des voies aériennes, toux possible avant curarisation, projections abondantes. Le statut microbiologique n’est pas encore connu."],
  ["Contrôler le matériel","Plusieurs modèles de FFP2, une visière, des lunettes, des gants et des surblouses imperméables à manches longues sont disponibles."]
 ],
 steps:[
  {dim:"Repérage",label:"Évaluer le contexte",q:"Quel raisonnement guide le choix des EPI ?",multi:false,correct:[0],critical:false,
   options:["Combiner le risque infectieux respiratoire, la proximité du geste et l’exposition aux sécrétions.","Choisir seulement selon le nom du geste, sans tenir compte du patient.","Attendre le résultat de PCR avant de choisir une protection.","Mettre tous les EPI disponibles sans analyser leur utilité."],
   explanation:"La SF2H fonde l’analyse sur l’agent, l’environnement et l’exposition : proximité, durée et type de soin. Ce cas concerne explicitement une infection respiratoire transmissible suspectée et un geste exposant. Il ne fixe pas une règle indifférenciée pour toutes les intubations.",
   good:"Vous reliez la protection au contexte clinique et à votre exposition réelle.",
   bad:"Le choix doit être raisonné rapidement avec le senior, sans attendre la microbiologie ni multiplier les équipements sans objectif.",
   takeaway:"Le bon EPI dépend du patient, du geste et de l’exposition.",sources:["resp","ps"]},
  {dim:"Protection",label:"Composer votre équipement",q:"Pour le contexte décrit, sélectionnez les quatre éléments à associer à l’hygiène des mains.",multi:true,correct:[0,1,2,3],critical:true,
   options:["APR FFP2 adapté au visage et correctement ajusté.","Protection oculaire : visière ou lunettes de protection.","Gants de soins adaptés au geste.","Surblouse imperméable à manches longues, compte tenu des projections abondantes.","Masque chirurgical à la place du FFP2.","Surchaussures systématiques à la place d’une protection oculaire."],
   explanation:"Le risque respiratoire justifie ici un FFP2 ; le contact avec les sécrétions et les muqueuses justifie les gants et la protection oculaire. La SF2H 2017, R16, préconise une surblouse imperméable à manches longues en cas d’exposition majeure aux produits biologiques ; une surblouse à manches longues plus tablier imperméable constitue une alternative. Les surchaussures ne remplacent aucune de ces protections.",
   good:"L’équipement répond aux risques respiratoires, oculaires et de projection de ce cas.",
   bad:"La combinaison est incomplète ou contient un substitut inadapté. L’équipe corrige l’équipement pendant la préparation du geste.",
   takeaway:"Ici : FFP2, yeux protégés, gants et tenue adaptée aux projections.",sources:["resp","ps"]},
  {dim:"Gestes sûrs",label:"Juste avant l’entrée",q:"Le FFP2 présente une fuite latérale au contrôle d’étanchéité. Que faites-vous ?",multi:false,correct:[0],critical:true,
   options:["Réajuster puis recontrôler ; changer de modèle ou de taille si nécessaire, en coordonnant immédiatement avec l’équipe.","Ajouter un masque chirurgical par-dessus et considérer le problème résolu.","Le garder tel quel : un FFP2 protège quel que soit son ajustement.","Retarder toute préparation jusqu’à l’organisation d’un fit-test complet."],
   explanation:"Le fit-check vérifie l’étanchéité à chaque mise en place ; un modèle inadapté doit être remplacé. Le fit-test, organisé en amont, sert à identifier les modèles convenant au visage. La préparation de la protection et celle du soin urgent sont coordonnées, sans attente administrative.",
   good:"Le défaut d’étanchéité est corrigé avant l’exposition.",
   bad:"La fuite ne peut pas être ignorée ou corrigée par un simple empilement. Un équipement adapté est recherché immédiatement avec l’équipe.",
   takeaway:"Contrôler l’étanchéité à chaque mise en place du FFP2.",sources:["resp"]},
  {dim:"Coordination",label:"Après le geste",q:"Le patient est stabilisé. Quelle sortie de la séquence de soins est la plus sûre ?",multi:false,correct:[0],critical:true,
   options:["Retrait des EPI selon le protocole, en évitant les faces contaminées et avec hygiène des mains ; retrait du FFP2 hors de la zone d’exposition.","Retirer le FFP2 dans la chambre pour respirer plus facilement.","Conserver les gants pour préparer le dossier du patient suivant.","Laisser tous les EPI en place jusqu’à la fin de garde."],
   explanation:"Le déshabillage est une séquence à risque d’auto-contamination. Le protocole local précise les zones et l’ordre de retrait ; les précautions respiratoires renforcées prévoient le retrait du FFP2 après la sortie de la chambre. L’hygiène des mains et la gestion du matériel restent indispensables.",
   good:"La protection reste cohérente jusqu’à la fin de la séquence.",
   bad:"Le retrait peut créer une exposition après un geste pourtant bien protégé. Reprendre le protocole de déshabillage et signaler toute exposition accidentelle.",
   takeaway:"La protection se termine avec un retrait maîtrisé, pas avec la fin du geste.",sources:["resp","ps"]}
 ]
},
{
 id:"reb",code:"04",time:"00:30",location:"Accueil de nuit",title:"Le voyage ne dit pas tout",
 topic:"Repérage et alerte REB",duration:"5 min",level:"Relier les indices & alerter",
 intro:"Une patiente de 35 ans arrive avec fièvre et toux après une mission à l’étranger. Elle vous dit : « Plusieurs collègues sont malades aussi. » La scène est entièrement fictive, sans alerte épidémiologique réelle associée.",
 patient:"Patiente D · 35 ans",vitals:[["T°","39 °C"],["PA","112/70"],["FR","24/min"],["SpO₂","93 % AA"]],
 clues:[
  ["Reconstituer l’exposition","Elle a travaillé dans un établissement de soins où plusieurs pneumopathies sévères sont survenues. Le dernier contact rapproché date de huit jours."],
  ["Préciser la chronologie","Retour il y a quatre jours, début des symptômes il y a deux jours. Deux collègues présentent des signes similaires."],
  ["Lire la fiche d’alerte de l’exercice","Pour cet exercice uniquement : syndrome respiratoire fébrile et contact avec le cluster décrit dans les 14 jours précédant les symptômes. Cette fenêtre fictive n’est pas une définition utilisable en soins réels."]
 ],
 steps:[
  {dim:"Repérage",label:"Croiser les informations",q:"Sur quels éléments repose la suspicion REB dans cet exercice ?",multi:false,correct:[0],critical:true,
   options:["Symptômes, exposition documentée au cluster et délai compatible avec la fiche d’alerte de l’exercice.","Le seul retour d’un pays étranger.","La nationalité ou la langue de la patiente.","Uniquement la température supérieure à 38,5 °C."],
   explanation:"Le repérage COREB croise symptômes et exposition, avec un délai d’incubation compatible avec la définition de cas de la maladie. Ici, la fiche fictive rend le cas suspect ; en situation réelle, consulter les définitions et alertes en vigueur et solliciter le référent. Le voyage seul ne classe pas un patient REB.",
   good:"Vous formulez une suspicion argumentée, sans conclure à un diagnostic confirmé.",
   bad:"Un critère isolé ne suffit pas. L’exposition et la chronologie doivent être rapprochées des symptômes et de la définition de cas.",
   takeaway:"REB : symptômes + exposition + temporalité, pas « retour de voyage » seul.",sources:["reb","procedure"]},
  {dim:"Protection",label:"Les premières minutes",q:"Que faites-vous dès la suspicion ?",multi:true,correct:[0,1,2],critical:true,
   options:["Éloigner la patiente de la salle d’attente commune et organiser un espace dédié.","Mettre en œuvre les protections adaptées au risque suspecté selon le protocole REB, avec masque patient si toléré.","Évaluer la gravité et mobiliser le senior pour les soins nécessaires, tout en préparant l’alerte.","La renvoyer en taxi vers un autre établissement sans coordination.","Attendre une confirmation biologique avant toute mesure."],
   explanation:"Les mesures de protection commencent dès la suspicion, parallèlement à l’évaluation clinique et aux soins nécessaires. Elles sont adaptées à l’agent suspecté ; il n’existe pas une tenue unique valable pour tout REB. La procédure locale doit préciser les EPI, le circuit et les intervenants formés.",
   good:"La patiente est prise en charge sans rester exposante en salle d’attente.",
   bad:"Une mesure essentielle manque ou un déplacement non maîtrisé est proposé. L’équipe sécurise le lieu et poursuit l’évaluation sans attendre le diagnostic.",
   takeaway:"Protéger et soigner en parallèle, dès la suspicion.",sources:["reb","procedure"]},
  {dim:"Gestes sûrs",label:"Prélever sans improviser",q:"Le bilan nécessite des prélèvements. Quel principe retenez-vous ?",multi:false,correct:[0],critical:true,
   options:["Coordonner avec le senior, le référent et le laboratoire le prélèvement et son acheminement avant de l’envoyer.","Envoyer tous les tubes par le circuit pneumatique sans avertissement.","Ne plus réaliser aucun examen, même utile aux soins urgents.","Multiplier les prélèvements non prescrits pour accélérer l’identification."],
   explanation:"La coordination des acteurs et l’adaptation au risque suspecté sont au cœur de la procédure COREB. Les examens utiles ne sont pas abandonnés, mais leur réalisation et leur circuit sont sécurisés avec le laboratoire. Le transport pneumatique ne doit pas être improvisé pour des échantillons à risque.",
   good:"Le laboratoire peut préparer un circuit adapté au risque annoncé.",
   bad:"Un circuit non anticipé peut exposer d’autres professionnels. Le bilan est coordonné avant son acheminement.",
   takeaway:"Prévenir le laboratoire et convenir du circuit avant l’envoi.",sources:["procedure"]},
  {dim:"Coordination",label:"L’appel qui compte",q:"Quelle transmission et quelle alerte retenez-vous ?",multi:false,correct:[0],critical:true,
   options:["Transmettre au senior et au référent REB symptômes, exposition, dates, gravité et mesures prises ; articuler l’alerte avec le Centre 15 et l’ARS selon le circuit local, puis transmettre le suivi à l’EOH à ses horaires de présence.","Publier une alerte nominative sur les réseaux sociaux.","Attendre le lendemain sans mobiliser de senior ni déclencher le circuit d’alerte.","Annoncer un diagnostic confirmé et transférer sans régulation."],
   explanation:"COREB prévoit l’alerte du référent REB et du Centre 15 dès la suspicion, puis le partage avec les autres acteurs et autorités selon l’organisation. Le classement et l’orientation sont concertés ; un cas suspect n’est pas un cas confirmé. Un transport éventuel est organisé par la filière avec des équipes formées.",
   good:"Le relais dispose des informations nécessaires pour classer et orienter la patiente.",
   bad:"L’alerte doit être précoce, confidentielle et structurée. Vous reprenez la transmission avec le senior avant toute orientation.",
   takeaway:"Alerter tôt, transmettre précisément, orienter de façon coordonnée.",sources:["reb","procedure"]}
 ]
},
{
 id:"diphterie",code:"05",time:"02:10",location:"Box ORL des urgences",title:"Une angine pas comme les autres",
 topic:"Suspicion de diphtérie ORL",duration:"5 min",level:"Reconnaître, protéger & alerter",
 intro:"Un patient de 24 ans consulte pour une odynophagie depuis trois jours, une voix modifiée et une fébricule. Des dépôts grisâtres sont visibles dans le pharynx. Il n’a pas de détresse respiratoire immédiate. Le senior est disponible.",
 patient:"Patient E · 24 ans",vitals:[["T°","38 °C"],["PA","118/74"],["FC","108/min"],["SpO₂","97 % AA"]],
 clues:[
  ["Préciser l’aspect ORL","Le senior décrit des fausses membranes grisâtres adhérentes sur les amygdales, s’étendant vers la luette, avec adénopathies cervicales. Leur extension fait surveiller le risque d’obstruction des voies aériennes."],
  ["Explorer vaccination et expositions","Le patient pense avoir été vacciné enfant, sans carnet ni rappel documenté. Il revient d’un séjour dans une région où circule la diphtérie. On recherche aussi les contacts proches et les contacts animaux, sans déduire l’espèce de cette seule histoire."],
  ["Préparer les premières mesures","Une chambre individuelle est disponible. La consultation initiale est brève, sans geste générant des aérosols, dans un local à ventilation conforme. Le senior et le laboratoire sont joignables ; le senior organise l’avis infectiologique et le signalement à l’ARS sans attendre les résultats. Le suivi est transmis à l’EOH à ses horaires de présence."]
 ],
 steps:[
  {dim:"Repérage",label:"Identifier l’urgence",q:"Devant cette angine à fausses membranes, quelle décision prenez-vous ?",multi:false,correct:[0],critical:true,
   options:["Évoquer une diphtérie ORL, appeler le senior, évaluer la gravité et engager sans délai protection et alerte.","Écarter la diphtérie parce que le patient dit avoir été vacciné enfant.","Attendre le résultat d’un test streptococcique avant d’envisager d’autres mesures.","Renvoyer le patient avec un traitement symptomatique puisque la fièvre est modérée."],
   explanation:"Une angine à fausses membranes doit faire évoquer la diphtérie. La fébricule et un antécédent vaccinal ne permettent pas de l’exclure. Il faut évaluer le risque d’obstruction et les signes cardiaques ou neurologiques, mobiliser le senior et l’infectiologue, et engager les mesures de protection. Toute suspicion clinique de diphtérie ORL doit être signalée immédiatement par téléphone à l’ARS, en coordination avec le senior, sans attendre la confirmation microbiologique ni la disponibilité de l’EOH. Le suivi est tracé et transmis à l’EOH à ses horaires de présence.",
   good:"Le senior reprend immédiatement l’évaluation ; la protection, l’avis infectiologique et le signalement sont engagés.",
   bad:"La suspicion ne peut pas être écartée sur la fièvre ou la vaccination rapportée. Le senior réévalue le patient avant toute sortie.",
   takeaway:"Fausses membranes : évoquer la diphtérie et alerter sans attendre.",sources:["diph2011","diph2021"]},
  {dim:"Protection",label:"Sécuriser la consultation",q:"Pour la consultation initiale décrite, quelles mesures retenez-vous ?",multi:true,correct:[0,1,2],critical:true,
   options:["Installer le patient en chambre individuelle avec des précautions respiratoires dès la suspicion, en plus des précautions standard.","Porter un masque à usage médical pour cette consultation brève sans aérosolisation, et adapter les autres EPI au risque de contact avec les sécrétions ou de projection.","Faire porter un masque à usage médical au patient lors des déplacements indispensables, si toléré ; réévaluer vers un FFP2 en cas de geste ou d’exposition à risque élevé.","Se limiter aux précautions contact car les fausses membranes empêchent la transmission respiratoire.","Attendre la PCR tox positive avant de modifier le circuit d’accueil."],
   explanation:"Le HCSP préconise un isolement respiratoire de type gouttelettes dès la suspicion d’une forme ORL. La SF2H 2024 classe C. diphtheriae parmi les bactéries de catégorie A : les précautions respiratoires sont adaptées à l’exposition et à l’environnement, avec renforcement en cas d’exposition à risque élevé. Le masque à usage médical correspond à la consultation brève sans PGA décrite ici ; il ne constitue pas une règle pour tout geste. Gants en cas de contact avec les muqueuses ou sécrétions, protection oculaire et tenue selon le risque de projection, et hygiène des mains restent nécessaires.",
   good:"L’accueil est sécurisé sans attendre la microbiologie, avec une protection adaptée à l’exposition.",
   bad:"Le risque respiratoire doit être pris en compte dès la suspicion. Les EPI et le circuit sont corrigés avec le senior selon le protocole local avant la poursuite des soins.",
   takeaway:"Protéger dès la suspicion ; adapter les EPI au geste et au risque respiratoire.",sources:["diph2011","resp","ps"]},
  {dim:"Gestes sûrs",label:"Prélever et traiter sans attendre",q:"Un ECG révèle maintenant un trouble de conduction, jugé évocateur d’atteinte toxinique par le senior. La recherche du gène tox n’est pas encore disponible. Que retenez-vous ?",multi:false,correct:[0],critical:true,
   options:["Prévenir le laboratoire/CNR, organiser les prélèvements urgents sans retard préjudiciable, débuter l’antibiothérapie et organiser l’antitoxine en urgence avec les spécialistes, sans attendre la confirmation tox+.","Attendre le test d’Elek avant toute prise en charge spécifique.","Prescrire seulement un rappel vaccinal, qui neutralisera la toxine déjà présente.","Attendre la PCR tox pour appeler l’infectiologue, malgré les signes cardiaques."],
   explanation:"L’antibiothérapie d’une diphtérie ORL est débutée immédiatement après les prélèvements, réalisés sans retard préjudiciable. Prévenir le laboratoire permet d’organiser les prélèvements ORL, la culture, l’identification et la recherche urgente du gène tox avec le CNR. En présence de signes toxiniques, l’antitoxine doit être organisée en urgence avant même la confirmation tox+ : elle neutralise la toxine circulante, pas celle déjà fixée aux tissus. L’atteinte cardiaque impose surveillance et prise en charge spécialisée ; le choix des traitements, leur administration et la sécurisation des voies aériennes relèvent du senior et des spécialistes.",
   good:"Prélèvements, traitement et surveillance spécialisée sont coordonnés sans attendre les résultats confirmatoires.",
   bad:"Attendre la confirmation malgré les signes toxiniques serait préjudiciable. Le senior mobilise immédiatement l’infectiologue et l’équipe de soins critiques.",
   takeaway:"Signes toxiniques : l’antitoxine est une urgence, sans attendre la confirmation.",sources:["diph2021","diphcnr"]},
  {dim:"Coordination",label:"Du cas confirmé aux contacts",q:"Le lendemain, C. diphtheriae porteur du gène tox est confirmé. Le signalement initial à l’ARS a déjà été fait. Quelles suites organisez-vous ?",multi:true,correct:[0,1,2],critical:true,
   options:["Compléter la notification obligatoire et coordonner avec l’ARS, l’EOH et la santé au travail l’identification des contacts proches, y compris les soignants exposés sans protection adaptée.","Organiser pour les contacts proches de ce cas à C. diphtheriae tox+ des prélèvements, une antibioprophylaxie, une surveillance clinique et une vérification/mise à jour vaccinale, même s’ils sont déjà vaccinés.","Maintenir les précautions du cas confirmé jusqu’aux critères de levée : deux cultures négatives espacées d’au moins 24 h, prélevées au moins 24 h après la fin de l’antibiothérapie, avec décision médicale et EOH.","Lever les précautions après 48 h d’antibiotiques si le patient n’a plus de fièvre.","Exclure tous les contacts vaccinés de l’investigation et donner une antitoxine préventive aux autres."],
   explanation:"L’alerte téléphonique précoce n’attend pas le résultat ; la notification obligatoire concerne notamment l’isolement d’une corynébactérie du complexe diphtheriae portant le gène tox, quel que soit le résultat du test d’Elek. Pour ce cas confirmé à C. diphtheriae tox+, les contacts proches sont évalués et pris en charge même s’ils sont vaccinés : prélèvements puis antibioprophylaxie sans attendre leur culture, surveillance et mise à jour vaccinale si nécessaire. Il n’y a pas d’antitoxine en prophylaxie des contacts. La levée des précautions du cas repose sur les contrôles microbiologiques, pas sur la seule disparition de la fièvre. Ne pas transposer automatiquement cette stratégie à C. ulcerans : la conduite dépend de l’espèce, du statut tox et du contexte, avec investigation animale le cas échéant.",
   good:"Le cas confirmé et ses contacts disposent d’un suivi coordonné, avec des critères explicites de levée des précautions.",
   bad:"La vaccination n’écarte pas la prise en charge des contacts proches de ce cas tox+. Le senior et l’EOH reprennent la liste des exposés et les critères de levée.",
   takeaway:"Distinguer alerte et notification ; ne pas oublier les contacts vaccinés.",sources:["diph2011","diph2021","diphcnr","resp"]}
 ]
},
{
 id:"ebola",code:"06",time:"03:00",location:"SAU non établissement de référence",title:"Sans saignement, pas sans risque",
 topic:"Suspicion de fièvre hémorragique virale Ebola",duration:"5 min",level:"Exposition & circuit sécurisé",
 intro:"Une patiente de 31 ans présente fièvre, asthénie et diarrhée après une mission humanitaire. Elle ne saigne pas et reste stable. Cette situation fictive se déroule dans un SAU qui n’est pas un établissement de santé de référence (ESR).",
 patient:"Patiente F · 31 ans",vitals:[["T°","38,9 °C"],["PA","116/72"],["FC","102/min"],["SpO₂","98 % AA"]],
 clues:[
  ["Rechercher une exposition précise","Neuf jours avant les premiers symptômes, elle a nettoyé sans protection adaptée les vomissements d’un patient dont une infection à virus Ebola a ensuite été confirmée. Cette exposition est fictive, mais documentée dans le dossier de l’exercice."],
  ["Reconstituer les dates","Les premiers symptômes ont débuté hier. Absence d’hémorragie extériorisée ; diarrhée et asthénie importantes. Aucune procédure invasive n’a encore été réalisée."],
  ["Vérifier les ressources","Le senior et le référent infectiologue REB sont joignables. Une chambre individuelle et le circuit local d’alerte sont disponibles. Les examens et l’éventuel transfert doivent être coordonnés avec l’ESR."]
 ],
 steps:[
  {dim:"Repérage",label:"Le piège du mot hémorragique",q:"Comment interprétez-vous ce tableau ?",multi:false,correct:[0],critical:true,
   options:["Fièvre et symptômes digestifs après une exposition documentée, dans un délai compatible : suspecter Ebola et demander immédiatement l’expertise REB.","L’absence de saignement permet d’exclure Ebola.","La diarrhée prouve une gastro-entérite banale.","Seule la nationalité de la patiente détermine le classement."],
   explanation:"La fiche COREB du 16 septembre 2026 associe des signes cliniques compatibles à une exposition datant de moins de 21 jours. Les manifestations hémorragiques peuvent être absentes au début. Ici, le contact non protégé avec les vomissements d’un cas confirmé et la chronologie justifient la suspicion ; le classement est concerté avec les experts, pas déduit d’un symptôme isolé.",
   good:"L’exposition décisive est identifiée, même sans saignement.",
   bad:"L’absence d’hémorragie ne suffit pas à rassurer. Le senior reprend immédiatement l’évaluation de l’exposition.",
   takeaway:"Ebola : l’exposition et le délai comptent ; ne pas attendre une hémorragie.",sources:["ebola"]},
  {dim:"Protection",label:"Ne pas improviser une intervention",q:"Quelles mesures engagez-vous immédiatement ?",multi:true,correct:[0,1,2],critical:true,
   options:["Isoler en chambre individuelle, limiter les contacts et proposer masque médical et hygiène des mains à la patiente si compatibles avec son état.","Mobiliser le senior et une équipe entraînée, équipée selon le protocole FHV, plutôt que d’entrer seul avec une tenue improvisée.","Poursuivre l’évaluation de gravité en limitant l’exposition et préparer l’appel au référent REB et au Centre 15.","Entrer seul avec un masque chirurgical et des gants pour gagner du temps.","Laisser la patiente dans le couloir tant qu’elle ne saigne pas."],
   explanation:"Le patient est isolé dès la suspicion. En SAU non ESR, COREB prévoit une évaluation par un senior formé et des EPI spécifiques FHV ; un masque et des gants seuls ne constituent pas cette protection. Le rôle de l’interne est de repérer, alerter et organiser le relais, sans s’exposer dans une intervention autonome non préparée. La protection n’interrompt pas la surveillance ni l’évaluation des besoins urgents.",
   good:"L’équipe protège la patiente et les professionnels sans improviser le circuit.",
   bad:"La suspicion impose une organisation dédiée et des professionnels entraînés. Le senior sécurise le relais avant tout contact exposant.",
   takeaway:"Isoler, alerter et mobiliser une équipe formée : pas d’intervention isolée improvisée.",sources:["ebola","procedure"]},
  {dim:"Gestes sûrs",label:"Le bilan habituel peut attendre le bon circuit",q:"La patiente est stable. Une NFS, un bilan hépatique et un test paludisme sont proposés au poste de soins. Que faites-vous ?",multi:false,correct:[0],critical:true,
   options:["Ne pas lancer de prélèvement de routine dans ce SAU non ESR ; convenir avec l’expert REB de l’évaluation et du circuit sécurisé, y compris pour les diagnostics alternatifs.","Faire immédiatement les tubes et les envoyer par pneumatique sans prévenir.","Poser une voie veineuse systématique avant d’appeler, même sans besoin thérapeutique urgent.","Abandonner définitivement toute recherche de paludisme ou de sepsis."],
   explanation:"Pour un patient suspect FHV en SAU non ESR, la fiche COREB 2026 prévoit de ne pas réaliser d’examens complémentaires ni de gestes invasifs sans nécessité thérapeutique urgente. Les diagnostics différentiels, notamment paludisme et sepsis, restent indispensables, mais leur exploration est organisée dans le circuit spécialisé. En cas d’aggravation, les soins urgents sont coordonnés immédiatement avec le senior, le SAMU et l’ESR : il ne s’agit pas de laisser un patient sans soins.",
   good:"Le diagnostic reste un objectif, dans un circuit qui ne crée pas d’exposition biologique évitable.",
   bad:"Un bilan non anticipé exposerait les préleveurs et le laboratoire. Le senior coordonne les examens et les soins nécessaires avec l’ESR.",
   takeaway:"FHV en SAU non ESR : pas de bilan de routine improvisé ; organiser l’expertise et les soins.",sources:["ebola"]},
  {dim:"Coordination",label:"Orienter et retrouver les exposés",q:"La suspicion est retenue après expertise. Quel relais organisez-vous ?",multi:false,correct:[0],critical:true,
   options:["Coordination référent REB, SAMU/Centre 15 et ARS pour l’orientation vers l’ESR ; documenter immédiatement les contacts et expositions, puis transmettre le suivi à l’EOH et à la santé au travail à leurs horaires de présence.","Demander à la famille de conduire la patiente à l’ESR.","Attendre une PCR positive avant de signaler la suspicion retenue.","Annoncer un cas confirmé à tout le personnel avec diffusion nominative non nécessaire."],
   explanation:"L’orientation d’une suspicion FHV validée est organisée avec les experts, les autorités et le SAMU vers une structure adaptée. Les contacts et co-exposés sont recensés immédiatement avec le senior et les acteurs mobilisés pour l’alerte, en distinguant suspicion et confirmation. Toute exposition professionnelle impose une évaluation urgente selon le circuit local, sans attendre l’ouverture de l’EOH ou de la santé au travail ; ces équipes reprennent le suivi à leurs horaires de présence.",
   good:"Le transfert est régulé et les expositions peuvent être évaluées sans retard.",
   bad:"Ni transport personnel ni attente de confirmation : l’orientation et la gestion des exposés nécessitent une coordination immédiate.",
   takeaway:"Transfert régulé, statut exact et traçabilité des expositions.",sources:["ebola","procedure"]}
 ]
},
{
 id:"mers",code:"07",time:"04:00",location:"Consultation de nuit",title:"Une toux presque banale",
 topic:"MERS-CoV après exposition en milieu de soins",duration:"5 min",level:"Reconnaître une forme peu sévère",
 intro:"Un soignant de 46 ans consulte pour fièvre et toux depuis ce matin. Il ne présente ni détresse respiratoire ni besoin d’oxygène. Il revient d’une mission en Arabie saoudite. Scénario fictif fondé sur la définition nationale de juin 2024, à réactualiser en situation réelle.",
 patient:"Patient G · 46 ans",vitals:[["T°","38,2 °C"],["PA","124/76"],["FR","18/min"],["SpO₂","97 % AA"]],
 clues:[
  ["Préciser la mission","Il a exercé dans un service hospitalier en Arabie saoudite. Son dernier jour d’activité dans cet établissement date de huit jours avant le début des symptômes."],
  ["Ne pas s’arrêter à la gravité","Toux et fièvre, sans hypoxémie. L’absence de contact connu avec un dromadaire ne résume pas les expositions possibles."],
  ["Consulter la définition datée","La définition Santé publique France de juin 2024 inclut une infection respiratoire aiguë de toute gravité après certaines expositions dans les 14 jours avant les symptômes, notamment une activité professionnelle en établissement de santé d’un pays à risque. L’Arabie saoudite figure dans cette liste datée."]
 ],
 steps:[
  {dim:"Repérage",label:"Une autre porte d’entrée dans la définition",q:"Ce patient doit-il faire discuter un classement comme cas possible de MERS-CoV ?",multi:false,correct:[0],critical:true,
   options:["Oui : infection respiratoire aiguë et activité professionnelle hospitalière dans un pays à risque huit jours auparavant, même sans pneumopathie sévère.","Non : une SpO₂ normale exclut nécessairement un cas possible.","Non : il n’a jamais touché de dromadaire.","Oui, uniquement parce qu’il a pris un avion."],
   explanation:"La définition de juin 2024 distingue plusieurs situations. La branche fondée sur certaines expositions, dont une activité professionnelle dans un établissement de santé d’un pays à risque, retient une infection respiratoire aiguë quelle que soit sa gravité dans les 14 jours suivant cette exposition. Ne pas lui appliquer à tort l’exigence de pneumopathie sévère d’une autre branche. La liste géographique et la définition en vigueur doivent être vérifiées avec le référent.",
   good:"Vous utilisez la bonne branche de la définition au lieu d’attendre une aggravation.",
   bad:"La faible gravité n’exclut pas le classement après cette exposition hospitalière. Le référent est sollicité.",
   takeaway:"MERS : certaines expositions rendent pertinente une forme respiratoire peu sévère.",sources:["mersdef"]},
  {dim:"Protection",label:"Avant la confirmation",q:"Quelles mesures préparez-vous avec le senior selon le protocole local ?",multi:true,correct:[0,1,2],critical:true,
   options:["Chambre individuelle et précautions Air et Contact, en plus des précautions standard, avec environnement adapté.","FFP2 ajusté, surblouse et gants selon le protocole MERS ; protection oculaire lors des soins exposants et hygiène des mains.","Masque médical au patient si toléré pour les déplacements indispensables, avec circuit anticipé.","Masque chirurgical seul pour le professionnel puisque le patient n’est pas hypoxémique.","Maintien dans la salle d’attente jusqu’au résultat de PCR."],
   explanation:"Le HCSP préconise dès la suspicion de MERS-CoV des précautions Air et Contact. Le senior met en œuvre les EPI, les locaux et les circuits prévus dans le protocole préparé en amont avec l’EOH ; un FFP2 doit être ajusté avant l’exposition. Il sollicite l’expertise REB en cas de difficulté, sans attendre la présence de l’EOH. Ce référentiel de prise en charge, daté de 2015, doit être articulé avec les procédures locales actualisées et l’expertise REB, tandis que le classement du cas utilise ici la définition de 2024.",
   good:"La faible gravité ne conduit pas à diminuer la prévention de la transmission.",
   bad:"Les protections ne dépendent pas de la seule saturation. Le circuit et l’équipement sont corrigés avant l’exposition.",
   takeaway:"Suspicion de MERS : protections respiratoires et contact sans attendre la PCR.",sources:["mersprec","resp"]},
  {dim:"Gestes sûrs",label:"Un premier prélèvement négatif",q:"Un prélèvement respiratoire haut réalisé très précocement revient négatif. Quelle décision est la plus sûre ?",multi:false,correct:[0],critical:true,
   options:["Réévaluer avec l’infectiologue et le laboratoire la qualité, le site et le moment du prélèvement ; maintenir les mesures tant que l’expertise n’a pas levé la suspicion.","Lever automatiquement toutes les précautions dès ce premier résultat.","Réaliser seul un lavage broncho-alvéolaire au box.","Envoyer le prochain prélèvement sans identification du risque."],
   explanation:"Un résultat négatif précoce sur un prélèvement respiratoire haut ne suffit pas, à lui seul, à exclure le diagnostic. Le HCSP souligne l’intérêt des prélèvements respiratoires bas et d’une réévaluation des prélèvements selon le contexte. Leur indication et leur réalisation sont spécialisées : il ne s’agit pas de prescrire automatiquement un geste invasif. Le laboratoire et le circuit d’acheminement sont prévenus et sécurisés.",
   good:"Le résultat est interprété avec le contexte clinique et l’exposition.",
   bad:"Un résultat isolé ne remplace pas la réévaluation spécialisée. Les mesures sont maintenues pendant cette réévaluation.",
   takeaway:"Un négatif précoce n’est pas une levée automatique de suspicion.",sources:["mersprec"]},
  {dim:"Coordination",label:"Transmettre les bons critères",q:"Que transmettez-vous pour organiser le classement et l’orientation ?",multi:false,correct:[0],critical:true,
   options:["Symptômes et gravité, dates exactes de travail hospitalier et de début des signes, protections et résultats ; coordination senior, référent REB, ARS et Centre 15 selon le circuit, avec suivi transmis à l’EOH à ses horaires de présence.","Seulement la destination touristique, sans les dates ni l’activité hospitalière.","Un diagnostic confirmé de MERS malgré l’absence de confirmation biologique.","Une demande de transfert non régulé en transports en commun."],
   explanation:"L’exposition professionnelle et sa chronologie sont déterminantes pour le classement. L’alerte et l’orientation sont concertées avec les acteurs REB et les autorités ; l’équipe receveuse et le transport éventuel sont préparés. Un cas possible ne devient pas confirmé sur le seul interrogatoire.",
   good:"Le référent dispose des informations qui changent réellement le classement.",
   bad:"La transmission est reprise avec les dates et l’exposition précise avant toute orientation.",
   takeaway:"Transmettre l’activité hospitalière et les dates, pas seulement le pays.",sources:["mersdef","mersprec","procedure"]}
 ]
},
{
 id:"zoonotique",code:"08",time:"05:10",location:"Filière de consultation",title:"Un œil rouge, une exposition",
 topic:"Suspicion de grippe zoonotique",duration:"5 min",level:"Penser au risque professionnel",
 intro:"Une professionnelle de 39 ans consulte pour une conjonctivite depuis hier. Elle n’a ni toux ni dyspnée. Elle a participé à une intervention dans un élevage avicole. L’épisode animal et la patiente sont fictifs.",
 patient:"Patiente H · 39 ans",vitals:[["T°","37,4 °C"],["PA","122/74"],["FR","16/min"],["SpO₂","99 % AA"]],
 clues:[
  ["Rechercher l’exposition animale","Trois jours avant les signes oculaires, elle a manipulé des volailles infectées par un virus influenza aviaire dans un foyer confirmé par les services vétérinaires de l’exercice."],
  ["Préciser la protection lors de l’intervention","Une projection a atteint son visage alors qu’elle ne portait pas de protection oculaire. Elle s’est ensuite frotté l’œil."],
  ["Vérifier le circuit diagnostique","Le laboratoire peut organiser une PCR influenza A/B et le sous-typage H1/H3. Le référent REB est joignable. Un test antigénique rapide négatif a été réalisé avant son arrivée."]
 ],
 steps:[
  {dim:"Repérage",label:"Au-delà du syndrome grippal",q:"Faut-il évoquer une grippe zoonotique malgré l’absence de fièvre et de toux ?",multi:false,correct:[0],critical:true,
   options:["Oui : une conjonctivite même isolée, après exposition avérée dans un délai compatible, justifie la suspicion et l’avis REB.","Non : une grippe zoonotique impose toujours une pneumopathie sévère.","Non : le test antigénique négatif élimine ce risque.","Oui, mais seulement si la patiente revient de l’étranger."],
   explanation:"La fiche COREB de novembre 2025 inclut la conjonctivite même isolée en cas d’exposition avérée, avec des signes survenant dans les dix jours suivant l’exposition. Le contexte professionnel documenté compte davantage qu’un voyage. Un test antigénique rapide ne permet pas d’exclure une grippe zoonotique.",
   good:"Vous reliez le symptôme oculaire à l’exposition animale documentée.",
   bad:"Une conjonctivite isolée peut faire partie du tableau. Le référent est appelé avant de banaliser la situation.",
   takeaway:"Conjonctivite + exposition avérée : penser à la grippe zoonotique.",sources:["zooflu","zoospf"]},
  {dim:"Protection",label:"Protéger aussi les yeux du soignant",q:"Quelles mesures retenez-vous pour la prise en charge ?",multi:true,correct:[0,1,2],critical:true,
   options:["Chambre individuelle, masque médical si toléré et hygiène des mains pour la patiente.","Équipe expérimentée avec FFP2, protection oculaire, surblouse et une paire de gants non stériles, avec hygiène des mains.","Limiter et regrouper les contacts nécessaires, avec avis du référent REB pour le circuit.","Supprimer toute protection respiratoire puisque la patiente ne tousse pas.","Remplacer la protection oculaire par une deuxième paire de gants."],
   explanation:"La fiche COREB prévoit des mesures renforcées REB respiratoires/contact : FFP2, lunettes, surblouse, une paire de gants et hygiène des mains. Elle privilégie une équipe expérimentée et entraînée, travaillant en binôme, sans exposer des étudiants à des soins non préparés. La présentation oculaire n’autorise pas à ignorer le risque respiratoire ni le risque de contact.",
   good:"Les protections répondent au risque suspecté, pas seulement au symptôme visible.",
   bad:"L’absence de toux ne permet pas de supprimer les mesures prévues. Le senior réorganise le circuit et la protection.",
   takeaway:"Grippe zoonotique suspectée : ne pas oublier FFP2 et protection oculaire.",sources:["zooflu"]},
  {dim:"Gestes sûrs",label:"Le bon test, au bon endroit",q:"Quels prélèvements et analyses organisez-vous avec le laboratoire ?",multi:false,correct:[0],critical:true,
   options:["PCR influenza A/B avec sous-typage H1/H3, écouvillon nasopharyngé même sans symptôme respiratoire et prélèvement conjonctival en présence de conjonctivite, dans un circuit sécurisé.","Un deuxième test antigénique rapide uniquement.","Un prélèvement conjonctival sans prévenir le laboratoire ni rechercher influenza.","Aucun prélèvement tant qu’il n’y a pas d’hypoxémie."],
   explanation:"COREB recommande une PCR influenza A/B avec sous-typage H1/H3. Le prélèvement nasopharyngé reste indiqué même sans signes respiratoires ; un écouvillon conjonctival est associé en cas de conjonctivite. Le laboratoire est prévenu pour organiser l’analyse, l’éventuel recours à l’ESR/CNR et le transport adapté. Un test antigénique rapide ne remplace pas cette stratégie.",
   good:"Les prélèvements permettent d’explorer une grippe zoonotique sans s’arrêter à un test inadapté.",
   bad:"La stratégie diagnostique est reprise avec le laboratoire ; le test antigénique ne suffit pas.",
   takeaway:"PCR A/B + sous-typage, prélèvements respiratoire et oculaire adaptés.",sources:["zooflu"]},
  {dim:"Coordination",label:"Probable ne signifie pas confirmé",q:"La PCR est positive pour influenza A ; le sous-typage saisonnier H1/H3 est négatif. Que faites-vous ?",multi:false,correct:[0],critical:true,
   options:["Signaler sans délai à l’ARS ce cas probable dans ce contexte, maintenir les mesures et organiser l’expertise/confirmation CNR ; préparer la recherche des contacts et co-exposés.","Annoncer immédiatement une infection H5N1 confirmée.","Lever les mesures parce que H1 et H3 sont négatifs.","Attendre plusieurs jours une éventuelle aggravation avant de contacter l’ARS."],
   explanation:"Dans ce contexte compatible, Santé publique France classe comme probable un cas positif pour influenza A avec sous-typage saisonnier H1/H3 négatif ou non concluant. Le signalement à l’ARS est immédiat et la confirmation relève du CNR. Ce résultat ne prouve pas à lui seul un sous-type H5N1. Le suivi des contacts et co-exposés est organisé avec les autorités, sans inventer une prophylaxie autonome.",
   good:"Vous alertez au bon stade, sans annoncer un sous-type non démontré.",
   bad:"Le statut exact et le signalement sont corrigés : il s’agit d’un cas probable à confirmer, pas d’une grippe saisonnière rassurante.",
   takeaway:"Influenza A non saisonnier dans ce contexte : alerte ARS et confirmation CNR.",sources:["zoospf","zooflu"]}
 ]
},
{
 id:"retour",code:"09",time:"06:20",location:"Relève des urgences",title:"Le voyage n’est pas le diagnostic",
 topic:"Contre-exemple REB : ne pas manquer un paludisme",duration:"5 min",level:"Trier sans banaliser",
 intro:"Un patient de 28 ans consulte pour fièvre et frissons dix jours après un séjour en zone de transmission palustre. La relève s’inquiète : « Retour de voyage, on déclenche forcément la filière REB ? » Le patient et le voyage sont fictifs.",
 patient:"Patient I · 28 ans",vitals:[["T°","39,2 °C"],["PA","116/70"],["FC","112/min"],["SpO₂","98 % AA"]],
 clues:[
  ["Explorer toutes les expositions","Piqûres de moustiques rapportées. Pas de contact avec malade, de soins hospitaliers, d’exposition animale particulière ni d’exposition aux liquides biologiques identifiés à l’interrogatoire."],
  ["Demander l’avis du senior","Dans le contexte fictif de ce dossier, le senior et le référent ont vérifié les itinéraires, dates et alertes applicables : aucune définition de cas REB particulière n’est retenue à ce stade. Ce constat n’est pas transposable à un voyage réel sans vérification."],
  ["Évaluer l’urgence clinique","Pas de trouble de conscience ni de détresse respiratoire à cet instant. La gravité doit néanmoins être réévaluée et une recherche de paludisme organisée en urgence, sans attendre une nouvelle poussée fébrile."]
 ],
 steps:[
  {dim:"Repérage",label:"Ni alerte automatique, ni banalisation",q:"Quelle conclusion retenez-vous après l’évaluation décrite ?",multi:false,correct:[0],critical:true,
   options:["Le voyage seul ne suffit pas à classer REB ; rechercher en urgence un paludisme et d’autres causes de fièvre, tout en réévaluant gravité et expositions.","Tout voyage à l’étranger impose un classement FHV, sans autre information.","L’absence de critère REB autorise un retour à domicile sans bilan.","Un paludisme est impossible parce que le patient ne saigne pas."],
   explanation:"Le repérage REB relie symptômes, expositions et temporalité à une définition actualisée. L’absence de critères après l’évaluation décrite ne rend pas cette fièvre bénigne : un paludisme doit être recherché sans délai. Cette situation illustre la distinction entre risque épidémique particulier et urgence clinique.",
   good:"Vous évitez l’étiquette automatique sans perdre de vue une urgence potentiellement grave.",
   bad:"Ne pas retenir un REB n’équivaut pas à autoriser une sortie. Le senior organise sans délai le bilan de fièvre au retour.",
   takeaway:"Pas de critère REB ne signifie pas absence d’urgence.",sources:["reb","procedure","malaria"]},
  {dim:"Protection",label:"Une protection proportionnée",q:"Dans le contexte évalué, quelles mesures maintenez-vous ?",multi:true,correct:[0,1,2],critical:false,
   options:["Précautions standard pour les soins, avec hygiène des mains et prévention des accidents d’exposition au sang.","EPI adaptés au geste et au risque de contact avec le sang ou de projection lors des prélèvements.","Réévaluation des précautions si un nouvel élément clinique ou d’exposition apparaît.","Tenue FHV systématique sur le seul retour d’un pays tropical.","Aucune protection pour manipuler le sang puisqu’il ne s’agit pas d’un REB retenu."],
   explanation:"Le paludisme n’impose pas à lui seul des précautions Air ou une tenue FHV : sa transmission habituelle est vectorielle, et une transmission par le sang est possible. Les précautions standard restent donc essentielles, notamment lors des prélèvements. Si l’évaluation découvre un autre risque infectieux, les mesures sont adaptées à ce nouveau risque.",
   good:"La protection reste pertinente et les prélèvements ne sont pas inutilement retardés.",
   bad:"La protection doit rester fondée sur le risque réel : ni suppression des précautions standard ni tenue FHV automatique.",
   takeaway:"Précautions standard maintenues ; mesures complémentaires selon le risque identifié.",sources:["malaria","ps","procedure"]},
  {dim:"Gestes sûrs",label:"Ne pas attendre le prochain frisson",q:"Comment organisez-vous la recherche de paludisme ?",multi:false,correct:[0],critical:true,
   options:["Prélever en urgence sans attendre un pic fébrile et demander un résultat diagnostique dans les deux heures, avec technique sensible et frottis selon le laboratoire.","Attendre le lendemain pour prélever pendant une nouvelle poussée fébrile.","Faire un test antigénique isolé et exclure définitivement le diagnostic s’il est négatif.","Attendre une aggravation neurologique avant de demander un bilan."],
   explanation:"La fiche INRS prévoit un diagnostic urgent, avec résultat dans les deux heures, sans attendre un pic fébrile. Le laboratoire associe une technique sensible à un frottis mince permettant notamment l’identification et l’évaluation de la parasitémie. Un premier bilan négatif avec suspicion persistante impose une réévaluation et, selon l’avis médical, de nouveaux prélèvements ; il n’autorise pas une exclusion automatique.",
   good:"Le bilan urgent est lancé et son résultat sera activement suivi.",
   bad:"Attendre expose à un retard diagnostique. Le senior contacte le laboratoire et organise la surveillance.",
   takeaway:"Paludisme suspecté : prélever maintenant et obtenir un résultat urgent.",sources:["malaria"]},
  {dim:"Coordination",label:"Ne pas fermer le raisonnement",q:"Le frottis confirme un paludisme. Quelle transmission est la plus sûre ?",multi:false,correct:[0],critical:true,
   options:["Transmettre immédiatement au senior pour évaluation de gravité et traitement ; garder la trace des expositions recherchées et rouvrir l’évaluation REB si un élément compatible nouveau apparaît.","Conclure qu’un paludisme exclut toute co-infection et toute nouvelle évaluation REB.","Autoriser une sortie automatique puisque le diagnostic est trouvé.","Différer l’information jusqu’à la fin de la relève."],
   explanation:"Un paludisme confirmé impose une prise en charge médicale urgente adaptée à la gravité. Un diagnostic alternatif ne doit pas effacer une exposition REB pertinente qui serait découverte ensuite : une co-infection reste possible. Dans ce dossier, l’absence de critères REB repose sur l’évaluation documentée, pas sur le seul résultat positif du paludisme. Le traitement relève du senior et de l’infectiologue.",
   good:"La relève reçoit le résultat, l’urgence de prise en charge et les éléments qui permettraient de réévaluer le risque.",
   bad:"Trouver un diagnostic n’autorise ni une sortie automatique ni la fermeture du raisonnement. Le senior reprend immédiatement la prise en charge.",
   takeaway:"Traiter l’urgence et rester disponible à une nouvelle information d’exposition.",sources:["malaria","ebola","procedure"]}
 ]
}
];
